version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.3.0
    environment:
      - APP_ID: bdbliblipiempfdkkkjohnecmeknnpoa
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            yarn install --immutable
            sudo apt-get update
            sudo apt-get -y install curl jq
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run:
          name: Build Project
          command: |
            yarn prod
      - run:
          name: Update secrets
          command: |
            cat << EOF > build/api-keys.json
            {"googleDrive": $json_api_key, "clientSecret": $json_client_secret}
            EOF
      - run:
          name: "Run Tests"
          command: yarn test
      - run:
          name: "Package Extension"
          command: |
            cd build
            zip -r ../tabox.zip *
            cd ..
      - store_artifacts:
          path: /build/tabox.zip
      - store_test_results:
          path: ~/test-results/jest/
      - run:
          name: "Upload & Publish Extension to the Google Chrome Store"
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&refresh_token=${REFRESH_TOKEN}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
              curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T tabox.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID}"
              curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID}/publish"
            fi